import Link from 'next/link'
import PackmanIcon from '../../assets/icons/packman.svg'
import UkrajineIcon from '../../assets/icons/ukrajine.svg'
import SlovakiaIcon from '../../assets/icons/slovakia.svg'
import PresidentalIcon from '../../assets/icons/presidental.svg'

// TODO: This should be generated by apollo
type Tag = {
  id: string
  slug: string
  title: string
  icon: string
}

// TODO: Convert to object lookup or enum
function TagIcon(props: { icon: string }) {
  switch (props.icon) {
    case '1':
      return <PackmanIcon className="h-20px" />
    case '2':
      return <PresidentalIcon className="h-20px" />
    case '3':
      return <SlovakiaIcon className="h-20px" />
    case '4':
      return <UkrajineIcon className="h-20px" />
    default:
      return null
  }
}

export default function ArticleTags({ tags }: { tags: Tag[] }) {
  return (
    <div className="d-flex flex-wrap align-items-center justify-content-between">
      <div className="d-flex flex-wrap align-items-center">
        {tags.map((tag) => (
          <div key={tag.id}>
            <Link
              className="btn outline mb-2 h-44px me-2 fs-6 px-4 lh-1"
              href={'/tag/' + tag.slug}
            >
              <span className="d-flex me-1">
                <TagIcon icon={tag.icon} />
              </span>
              <span className="lh-1 m-0 p-0">{tag.title}</span>
            </Link>
          </div>
        ))}
      </div>
    </div>
  )
}
