version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    labels:
      - 'dependencies'
    schedule:
      interval: 'daily'
    open-pull-requests-limit: 10
    reviewers:
      - vaclavbohac
    target-branch: main
    versioning-strategy: lockfile-only
